# property of Alexix Dimitriadis

prefix skos:<http://www.w3.org/2004/02/skos/core#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

  

# Adapt these to your project
PREFIX ontology: <https://vocabulary.customer.com/MyProject/thesaurus/import/schema>
PREFIX thesaurus: <https://vocabulary.customer.com/MyProject/thesaurus>

SELECT ?subj ?slabel ?pred ?olabel  

WHERE

{

  GRAPH thesaurus: {

    GRAPH ontology: {

     # a property with a range, defined in the ontology
     ?pred rdfs:range ?range .
     ?range a owl:Class .

    }

    # used in a way that violates the range
    ?subj ?pred ?val .

    FILTER NOT EXISTS { ?val a ?range } .

    ?val skos:prefLabel ?olabel .

    ?subj skos:prefLabel ?slabel .

  }

}

ORDER BY ?pred ?slabel ?olabel
